#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Illuminate\Container\Container;

$autoloadFile = '/vendor/autoload.php';

if (file_exists(__DIR__.$autoloadFile)) {
    require __DIR__.$autoloadFile;
} elseif (file_exists(getcwd().$autoloadFile)) {
    require getcwd().$autoloadFile;
}

# ------------------------------------------------------------------------------

$container = new Container;
$app = new Application('Essential', 'v0.1');

foreach (require(__DIR__.'/commands.php') as $command) {
    $commandInstance = new $command;
    $commandInstance->setLaravel($container);

    $app->add($commandInstance);
}


$app->run();
